# SVR

## Importing the libraries

In [5]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Data Set Import

In [6]:
data_set = pd.read_csv('../Model Selection - Combined Cycl.csv')
X = data_set.iloc[:, :-1].values
y = data_set.iloc[:, -1].values

In [7]:
y = y.reshape(len(y),1)

## Splitting the dataset into the Training & Test set

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Feature Scaling

In [9]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
sc_y = StandardScaler()
X_train = sc_X.fit_transform(X_train)
y_train = sc_y.fit_transform(y_train)
print(y_train)
y_train=np.ravel(y_train)
print(y_train)

[[ 1.15069786]
 [ 0.79540777]
 [-1.30936356]
 ...
 [ 0.27595724]
 [ 0.49346982]
 [-1.53508417]]
[ 1.15069786  0.79540777 -1.30936356 ...  0.27595724  0.49346982
 -1.53508417]


## SVR model Training on the Training set

In [10]:
from sklearn.svm import SVR
regressor = SVR(kernel = 'rbf')
regressor.fit(X_train, y_train)

SVR()

## Test set results Predictions

In [11]:
X_test=sc_X.fit_transform(X_test)
y_pred=regressor.predict(X_test)
y_predict= sc_y.inverse_transform([y_pred])
y_predict=y_predict.reshape(-1,1)
print(y_predict)
print(y_test)


#  y_pred = sc_y.inverse_transform(regressor.predict(sc_X.transform(X_test)))
np.set_printoptions(precision=2)
print(np.concatenate((y_predict.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[434.49984934]
 [457.70985097]
 [460.84909947]
 ...
 [470.22304261]
 [439.28872637]
 [460.42910288]]
[[431.23]
 [460.01]
 [461.14]
 ...
 [473.26]
 [438.  ]
 [463.28]]
[[434.5  431.23]
 [457.71 460.01]
 [460.85 461.14]
 ...
 [470.22 473.26]
 [439.29 438.  ]
 [460.43 463.28]]


## Model Performance Evaluation

In [13]:
from sklearn.metrics import r2_score
r2_score(y_test, y_predict)

0.9483693304317926